BestPurchase/Models/CartModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BestPurchase.ServiceLayer.Models
{
    public class CartModel
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? Price { get; set; }
        public int? Quantity { get; set; }
    }
    public class CartsCollection
    {
        public List<CartModel> ProductList { get; set; }
        public CartsCollection()
        {
            ProductList = new List<CartModel>();
        }
    }
}

BestPurchase/Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BestPurchase.ServiceLayer.Models
{
    public class OrderModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is required")]
        [DataType(DataType.Text)]
        public string FirstName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Address is required")]
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "E-Mail is required")]
        public string Email { get; set; }
        public string UserName { get; set; }
        public List<CartModel> Cart { get; set; }
        public OrderModel()
        {
            Cart = new List<CartModel>();
        }
    }
}

BestPurchase/Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace BestPurchase.ServiceLayer.Models
{
    public class ProductModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Price { get; set; }
        public string ProductCategory { get; set; }
        public int? Quantity { get; set; }
        public byte[] ImageStream { get; set; }
    }


    public class ProductsModel
    {
        public List<ProductModel> ProductList { get; set; }
        public ProductsModel()
        {
            ProductList = new List<ProductModel>();
        }
    }

    public enum CategoryModel
    {
        [Display(Name = "All Products")]
        AllProducts,

        [Display(Name = "Organic Products")]
        OrganicProducts,

        [Display(Name = "Meat Products")]
        MeatProducts,

        [Display(Name = "Fish And Sea Food")]
        FishAndSeaFood,

        [Display(Name = "Frozen Products")]
        FrozenProducts,
        Sweets
    }
}

BestPurchase/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BestPurchase.ServiceLayer.Models
{
    public class UserModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        public string UserName { get; set; }
    }
}

BestPurchase/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BestPurchase.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BestPurchase/Controllers/StorePageController.cs
using BestPurchase.DataModel;
using BestPurchase.ServiceLayer.Functionals;
using BestPurchase.ServiceLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace BestPurchase.ServiceLayer.Controllers
{
    public class StorePageController : Controller
    {
        // GET: StorePage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllProducts()
        {
            return View("GetAllProducts");
        }
        public PartialViewResult ShowFilteredCategory(int category)
        {
            Products products = Manager.Instance().GetProducts();
            ProductsModel prods = Manager.Instance().ConvertToServiceLayerEntity(products);
            if (category == 0)
            {
                return PartialView("ShowFilteredCategory", prods.ProductList);
            }
            Category cat = (Category)category;
            var filteredProducts = prods.ProductList.Where(c => c.ProductCategory ==
            Manager.Instance().ConvertFromEnumToString(cat)).ToList();
            return PartialView("ShowFilteredCategory", filteredProducts);
        }
        
        [HttpPost]
        public ActionResult AddToCart(CartModel cart)
        {
            var Cart = ShoppingCart.GetCart(this.HttpContext);
            Cart.Added.Id = cart.ProductId;
            Cart.Quantity = cart.Quantity;
            Manager.Instance().AddProductToCart(Cart);
            return View("AddToCart");
        }
        public PartialViewResult SelectQuantity(int Id)
        {
            CartModel cart = new CartModel();
            cart.ProductId = Id;
            return PartialView("SelectQuantity", cart);
        }
        public ActionResult GetShoppingCartContent()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ShoppingCartCollection cartCollection = Manager.Instance().GetShoppingCartContent(cart.CartId);
            CartsCollection carts = Manager.Instance().ConvertBLCartsToSLCarts(cartCollection);
            return View("GetShoppingCartContent", carts.ProductList);
        }
        public ActionResult DeleteItemFromCart(int productId)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.Added.Id = productId;
            Manager.Instance().DeleteItemFromCart(cart);
            ShoppingCartCollection cartCollection = Manager.Instance().GetShoppingCartContent(cart.CartId);
            CartsCollection carts = Manager.Instance().ConvertBLCartsToSLCarts(cartCollection);
            return View("GetShoppingCartContent", carts.ProductList);
        }
        public ActionResult AddOrder()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            OrderModel order = new OrderModel();
            ShoppingCartCollection cartCollection = Manager.Instance().GetShoppingCartContent(cart.CartId);
            CartsCollection carts = Manager.Instance().ConvertBLCartsToSLCarts(cartCollection);
            foreach (var item in carts.ProductList)
            {
                order.Cart.Add(item);
            }
            return View("AddOrder", order);
        }

        [HttpPost]
        public ActionResult AddOrder(OrderModel order)
        {
            Manager.Instance().AddOrder(order);
            var Cart = ShoppingCart.GetCart(this.HttpContext);
            foreach (var item in order.Cart)
            {
                ShoppingCart cart = Manager.Instance().ConvertCartModelToCart(item);
                cart.CartId = Cart.CartId;
                Manager.Instance().DeleteItemFromCart(cart);
            }
            ShoppingCartCollection cartCollection = Manager.Instance().GetShoppingCartContent(Cart.CartId);
            CartsCollection carts = Manager.Instance().ConvertBLCartsToSLCarts(cartCollection);
            return View("GetShoppingCartContent", carts.ProductList);
        }
        
        public ActionResult GetProductDetails(int productId)
        {
            Product product = Manager.Instance().GetProductById(productId);
            ProductModel pro = Manager.Instance().ConvertProductToProductModel(product);
            return View("GetProductDetails", pro);
        }
    }
}

BestPurchase/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BestPurchase/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BestPurchase/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

BestPurchase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Products", "GetAllProducts", "StorePage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shopping Cart", "GetShoppingCartContent", "StorePage")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BestPurchase/Views/StorePage/AddOrder.cshtml
@model BestPurchase.ServiceLayer.Models.OrderModel

@{
    ViewBag.Title = "User Details";
}

<h2>User Details</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
			<label style=" margin-right:20px;">First Name: </label>
                @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })<br>
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">Last Name: </label>
			@Html.TextBoxFor(x => x.LastName, new { @required = "required", @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">Address: </label>
			@Html.TextBoxFor(x => x.Address, new { @required = "required", @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">City: </label>
			@Html.TextBoxFor(x => x.City, new { @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">State: </label>
			@Html.TextBoxFor(x => x.State, new { @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">Postal Code: </label>
			@Html.TextBoxFor(x => x.PostalCode, new { @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">Country: </label>
			@Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">Phone: </label>
			@Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">E-Mail: </label>
			@Html.TextBoxFor(x => x.Email, new { @required = "required", @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

        <div class="form-group">
			<label style=" margin-right:20px;">Username: </label>
			@Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
			<br>
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
		<br />
		<br />
		@for (var i = 0; i < Model.Cart.Count(); ++i)
		{

			var item = Model.Cart[i];
			<div style="display: none;">@Html.EditorFor(model => model.Cart[i])</div>
		}
        <div class="form-group">
			<input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BestPurchase/Views/StorePage/AddToCart.cshtml
@{
	ViewBag.Title = "Product Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

BestPurchase/Views/StorePage/GetAllProducts.cshtml
<h2>Products Page</h2>
@{
	ViewBag.Title = "Available Products";
}

@Html.DropDownList("MyType",
	EnumHelper.GetSelectList(typeof(BestPurchase.ServiceLayer.Models.CategoryModel)),
	"Select Product Category",
	new { @class = "form-control", @id = "myDropDown" })
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
	$('#myDropDown').change(function () {

		var selectedID = $(this).val();

		$.get('/StorePage/ShowFilteredCategory?category=' + selectedID, function (data) {

			$('#toUpdate').html(data);

			$('#toUpdate').fadeIn('fast');
		});

	});
</script>

<div id="toUpdate"></div>
@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"> </script>

BestPurchase/Views/StorePage/GetProductDetails.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.Title = "Product Details";
}

<!DOCTYPE html>
@model BestPurchase.ServiceLayer.Models.ProductModel

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Get Product Details</title>
</head>
	<h1>Product Details</h1>
	<div class="container">

		<img src="data:image;base64,@System.Convert.ToBase64String(Model.ImageStream)" width="200" height="200"/>
	</div>

    <div> 
			<b>Product Name:</b> @Model.Name<br />
			<b>Product Category:</b>  @Model.ProductCategory<br />
			<b>Product Description:</b> @Model.Description<br />
			<b>Product Price:</b> @Model.Price<br />

		</div>

BestPurchase/Views/StorePage/GetShoppingCartContent.cshtml
@model List<BestPurchase.ServiceLayer.Models.CartModel>

@{
    ViewBag.Title = "Shopping Cart";
}

<h2>Shopping Cart</h2>
<style type="text/css">
	.webgrid-table {
		font-family: Arial,Helvetica,sans-serif;
		font-size: 14px;
		font-weight: normal;
		width: 650px;
		display: table;
		border-collapse: collapse;
		border: solid px #C5C5C5;
		background-color: white;
	}

		.webgrid-table td, th {
			border: 1px solid #C5C5C5;
			padding: 3px 7px 2px;
		}

	.webgrid-header, .webgrid-header a {
		background-color: #0094ff;
		color: #ffffff;
		text-align: left;
		text-decoration: none;
	}

	.webgrid-footer {
	}

	.webgrid-row-style {
		padding: 3px 7px 2px;
	}

	.webgrid-alternating-row {
		background-color: azure;
		padding: 3px 7px 2px;
	}

	.col1Width {
		width: 55px;
	}

	.col2Width {
		width: 220px;
	}
</style>

@{
	var grid = new WebGrid(source: Model, rowsPerPage: 3, columnNames: new[]
	{"ProductId", "ProductName", "Price", "Quantity"});
	grid.Pager(WebGridPagerModes.All);
}
@using (Html.BeginForm("AddToCart", "StorePage", FormMethod.Post, new { id = "form" }))
{
	int rowNum = 0;
	<div id="gridContent" style="font-family: Arial; padding: 20px;">
		@grid.GetHtml(tableStyle: "webgrid-table",
			headerStyle: "webgrid-header",
			footerStyle: "webgrid-footer",
			alternatingRowStyle: "webgrid-alternating-row",
			selectedRowStyle: "webgrid-selected-row",
			rowStyle: "webgrid-row-style",

			columns: grid.Columns(
			grid.Column("Row Number", format: item => rowNum = rowNum + 1),
			grid.Column(columnName: "ProductName", header: "Product Name", format: (item) => Html.ActionLink(((string)item.ProductName), "GetProductDetails", 
			new { productId = item.ProductId })),
			grid.Column(columnName: "Price", header: "Product Price"),
			grid.Column(columnName: "Quantity", header: "Quantity"),
			grid.Column(format: (item) => Html.ActionLink("Delete", "DeleteItemFromCart", new { productId = item.ProductId},
			new { onclick = "return confirm('Are you sure you want to delete this item?');" })),
			grid.Column(format: @<input type="hidden" name="Id" value="@item.ProductId" />)))
	</div>

}

@using (Html.BeginForm("GetPaymentAndShippingInfo", "StorePage", FormMethod.Post, new { id = "my-form" }))
{
	for (var i = 0; i < Model.Count(); ++i)
	{
		var item = Model[i];
		<div style="display: none;">@Html.EditorFor(model => model[i])</div>
	}
}
@{
	int? TotalPrice = 0;
	foreach (var item in Model)
	{
		TotalPrice += item.Price * item.Quantity;
	}
	<p>&nbsp &nbsp &nbsp <b>Total Price</b>&nbsp <input value=@TotalPrice readonly />&nbsp &nbsp &nbsp<input type="button" value="Checkout" id="myButtonId" 
	onclick="location.href='@Url.Action("AddOrder", "StorePage")'"/></p>

}

BestPurchase/Views/StorePage/SelectQuantity.cshtml
@model BestPurchase.ServiceLayer.Models.CartModel
@using (Html.BeginForm("actionName", "controllerName", FormMethod.Post, new { id = "my-form" }))
{
	@Html.TextBoxFor(x => x.Quantity)<br />
	@Html.HiddenFor(x => x.ProductId)<br />
	<input type="button" value="Submit" id="form-submit" />
}

BestPurchase/Views/StorePage/ShowFilteredCategory.cshtml
@{
	ViewBag.Title = "Products List";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
			.webgrid-table {
				font-family: Arial,Helvetica,sans-serif;
				font-size: 14px;
				font-weight: normal;
				width: 650px;
				display: table;
				border-collapse: collapse;
				border: solid px #C5C5C5;
				background-color: white;
			}

				.webgrid-table td, th {
					border: 1px solid #C5C5C5;
					padding: 3px 7px 2px;
				}

			.webgrid-header, .webgrid-header a {
				background-color: #0094ff;
				color: #ffffff;
				text-align: left;
				text-decoration: none;
			}

			.webgrid-footer {
			}

			.webgrid-row-style {
				padding: 3px 7px 2px;
			}

			.webgrid-alternating-row {
				background-color: azure;
				padding: 3px 7px 2px;
			}

			.col1Width {
				width: 55px;
			}

			.col2Width {
				width: 220px;
			}
		</style>

	@{
		ViewBag.Title = "Get All Products";
		var grid = new WebGrid(source: Model, rowsPerPage: 3, columnNames: new[]
		{"Name", "Description", "Price", "ProductCategory", "Quantity"});
		grid.Pager(WebGridPagerModes.All);
	}
		@using (Html.BeginForm("AddToCart", "StorePage", FormMethod.Post, new { id = "form" }))
		{
			int rowNum = 0;
			<div id="gridContent" style="font-family: Arial; padding: 20px;">
				@grid.GetHtml(tableStyle: "webgrid-table",
			headerStyle: "webgrid-header",
			footerStyle: "webgrid-footer",
			alternatingRowStyle: "webgrid-alternating-row",
			selectedRowStyle: "webgrid-selected-row",
			rowStyle: "webgrid-row-style",

			columns: grid.Columns(
			grid.Column("Row Number", format: item => rowNum = rowNum + 1),
			grid.Column(columnName: "Name", header: "Product Name"),
			grid.Column(columnName: "Description", header: "Product Description"),
			grid.Column(columnName: "ProductCategory", header: "Product Category"),
			grid.Column(columnName: "Price", header: "Product Price"),
			grid.Column(format: (item) => item.GetSelectLink("Add to Cart")),
			grid.Column(format: @<input type="hidden" name="Id" value="@item.Id" />)))
				@if (grid.HasSelection)
				{
					var pro = (BestPurchase.ServiceLayer.Models.ProductModel)grid.Rows[grid.SelectedIndex].Value;
					<p><b>Product Name:</b> @pro.Name</p>
					<p><b>Product Price:</b> @pro.Price</p>
					<p><b>Product Description:</b> @pro.Description</p>
					<p><b>Product Category:</b> @pro.ProductCategory</p>
					var product = (BestPurchase.ServiceLayer.Models.ProductModel)grid.Rows[grid.SelectedIndex].Value;
					var val = product.Id;

					@Ajax.ActionLink("Add Quantity", "SelectQuantity", new { Id = val }, new AjaxOptions()
			   {
				   HttpMethod = "GET",
				   InsertionMode = InsertionMode.InsertAfter,
				   UpdateTargetId = "posts-wrapper"
			   });
				}
			</div>
			<div id="posts-wrapper"></div>

		}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
	$(document).on('click', '#form-submit', function () {
		$.ajax({
			url: "AddToCart",
			type: "POST",
			data: $('form#my-form').serialize(),
			success: function (result) {
				window.location.href = '/StorePage/GetShoppingCartContent'
			},
		});
	});
</script>
@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"> </script>